# Generated by Django 3.1.7 on 2022-02-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0002_auto_20190603_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='encryption_key_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_ea', to='pyas2.privatekey'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signature_key_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sa', to='pyas2.privatekey'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, help_text='This email will be used for the Disposition-Notification-To header. If left blank, header defaults to: no-reply@pyas2.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cmd_receive',
            field=models.TextField(blank=True, help_text='Command executed after successful message receipt, replacements are $filename, $fullfilename, $sender, $receiver, $messageid and any message header such as $Subject', null=True, verbose_name='Command on Message Receipt'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cmd_send',
            field=models.TextField(blank=True, help_text='Command executed after successful message send, replacements are $filename, $sender, $receiver, $messageid and any message header such as $Subject', null=True, verbose_name='Command on Message Send'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='content_type',
            field=models.CharField(choices=[('application/EDI-X12', 'application/EDI-X12'), ('application/EDIFACT', 'application/EDIFACT'), ('application/edi-consent', 'application/edi-consent'), ('application/XML', 'application/XML'), ('application/octet-stream', 'binary')], default='application/edi-consent', max_length=100),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_key', models.CharField(choices=[('P', 'Primary'), ('A', 'Alternate')], default='P', max_length=2)),
                ('organization_auto_swap', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyas2.organization')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyas2.partner')),
            ],
        ),
    ]
