# Generated by Django 4.1 on 2023-01-12 11:50

from django.db import migrations, models
import pyas2.models


class Migration(migrations.Migration):

    dependencies = [
        ("pyas2", "0004_partner_canonicalize_as_binary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mdn",
            name="payload",
            field=models.FileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=pyas2.models.get_mdn_store,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="payload",
            field=models.FileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=pyas2.models.get_message_store,
            ),
        ),
    ]
