# Generated by Django 4.2.16 on 2024-09-23 16:00

from django.db import migrations, models
import pyas2.models


class Migration(migrations.Migration):

    dependencies = [
        ("pyas2", "0005_alter_mdn_payload_alter_message_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mdn",
            name="headers",
            field=models.FileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=pyas2.models.get_mdn_store,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="headers",
            field=models.FileField(
                blank=True,
                max_length=4096,
                null=True,
                upload_to=pyas2.models.get_message_store,
            ),
        ),
    ]
