# Generated by Django 4.2.16 on 2025-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyas2", "0006_alter_mdn_headers_alter_message_headers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="target_url",
            field=models.URLField(max_length=2048),
        ),
    ]
