# Generated by Django 5.2.7 on 2025-11-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyas2", "0007_alter_partner_target_url"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_id", "organization", "partner"],
                name="message_lookup_idx",
            ),
        ),
    ]
